print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/annastassen/PoeticLandscape/PoeticLandscape/Assets/models/table.mb"`)
{		
	file -o "/Users/annastassen/PoeticLandscape/PoeticLandscape/Assets/models/table.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/annastassen/PoeticLandscape/PoeticLandscape/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/annastassen/PoeticLandscape/PoeticLandscape/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/annastassen/PoeticLandscape/PoeticLandscape/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
